name: Brisbane Barre Studio
favicon: null
layout_spectrum: 0.65382
typography_spectrum: 0.67678
title: Brisbane Barre Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#eb0a8e'
    - '#fefefe'
    - '#c2c2c2'
    - '#727272'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
