name: Brisbane Barre Studio
favicon: null
layout_spectrum: 0.8795470327604562
typography_spectrum: 0.7285579084418714
title: Brisbane Barre Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.968901063548401
  lightness: 0.6812936102505773
  saturation: 0.4763342223595828
  rhythmicContrast: 0.23417649394832551
purpose: []
